# Generated by Django 5.2.14 on 2026-06-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Puede ver Rekium Stats'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TrackedCorporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporation_id', models.PositiveIntegerField(help_text='EVE Online Corporation ID', unique=True)),
                ('corporation_name', models.CharField(help_text='Nombre descriptivo (solo para referencia en el admin)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Desactiva para excluir temporalmente sin borrar')),
            ],
            options={
                'verbose_name': 'Corp rastreada',
                'verbose_name_plural': 'Corps rastreadas',
                'ordering': ['corporation_name'],
            },
        ),
    ]
