# Generated by Django 5.2.14 on 2026-06-02 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koru_stats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoonTaxConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='default', help_text='Nombre del perfil de tax', max_length=100, unique=True)),
                ('ubiquitous_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='% sobre valor mercado', max_digits=5)),
                ('common_rate', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('uncommon_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('rare_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('exceptional_rate', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de tax lunar',
                'verbose_name_plural': 'Configuración de tax lunar',
            },
        ),
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Puede ver Rekium Stats'), ('moon_tax_admin', 'Puede gestionar tax de lunas'))},
        ),
        migrations.AlterField(
            model_name='trackedcorporation',
            name='corporation_name',
            field=models.CharField(help_text='Nombre descriptivo', max_length=100),
        ),
        migrations.AlterField(
            model_name='trackedcorporation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MoonTaxPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField(db_index=True, help_text='eveonline_evecharacter.id del main')),
                ('character_name', models.CharField(max_length=100)),
                ('period', models.CharField(db_index=True, help_text='Formato YYYY-MM', max_length=7)),
                ('isk_owed', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas opcionales del director')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_by', models.ForeignKey(blank=True, help_text='Director/CEO que marcó el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moon_tax_payments_approved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax lunar — pago',
                'verbose_name_plural': 'Tax lunar — pagos',
                'ordering': ['-period', 'character_name'],
                'unique_together': {('character_id', 'period')},
            },
        ),
    ]
