# Generated by Django 5.2.14 on 2026-06-02 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koru_stats', '0002_moontaxconfig_alter_general_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Puede ver Estadísticas y Mi Dashboard'), ('corp_finance_access', 'Puede ver Finanzas Corp'), ('moon_tax_access', 'Puede ver Tax Lunas'), ('moon_tax_admin', 'Puede gestionar tax de lunas'))},
        ),
        migrations.AlterField(
            model_name='moontaxconfig',
            name='tag',
            field=models.CharField(default='default', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='moontaxconfig',
            name='ubiquitous_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='moontaxpayment',
            name='character_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='moontaxpayment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='moontaxpayment',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moon_tax_payments_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moontaxpayment',
            name='period',
            field=models.CharField(db_index=True, max_length=7),
        ),
    ]
