# Generated by Django 5.2.15 on 2026-06-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koru_stats', '0005_character_monthly_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterMonthlyOre',
        ),
        migrations.DeleteModel(
            name='CharacterMonthlySummary',
        ),
    ]
