# Generated by Django 5.2.15 on 2026-06-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koru_stats', '0007_restore_character_monthly_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermonthlyore',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='charactermonthlysummary',
            name='corporation_id',
            field=models.IntegerField(db_index=True, default=0, help_text='Corp del personaje al momento de la agregación'),
        ),
        migrations.AlterField(
            model_name='charactermonthlysummary',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='charactermonthlysummary',
            name='mining_isk',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ISK estimado a precio de mercado', max_digits=20),
        ),
        migrations.AlterField(
            model_name='charactermonthlysummary',
            name='period',
            field=models.CharField(db_index=True, help_text='Formato YYYY-MM', max_length=7),
        ),
    ]
