# Generated by Django 5.2.15 on 2026-06-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koru_stats', '0008_alter_charactermonthlyore_id_and_more'),
        ('koru_stats', '0008_ore_prices_pvp_module'),
    ]

    operations = [
    ]
