# Generated by Django 5.2.15 on 2026-06-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koru_stats', '0009_merge_20260607_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Puede ver Estadísticas y Mi Dashboard'), ('corp_finance_access', 'Puede ver Finanzas Corp'), ('moon_tax_access', 'Puede ver Tax Lunas'), ('moon_tax_admin', 'Puede gestionar tax de lunas'), ('pvp_access', 'Puede ver estadísticas PvP detalladas'), ('fc_access', 'Puede ver panel FC/Director'))},
        ),
        migrations.AlterField(
            model_name='charactermonthlyore',
            name='isk',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ISK a precio raw (market sell)', max_digits=20),
        ),
        migrations.AlterField(
            model_name='charactermonthlypvp',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='charactermonthlysummary',
            name='corporation_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='charactermonthlysummary',
            name='mining_isk',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ISK a precio raw (market sell)', max_digits=20),
        ),
        migrations.AlterField(
            model_name='charactermonthlysummary',
            name='period',
            field=models.CharField(db_index=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='oremarketprice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
