# Generated by Django 5.2.15 on 2026-06-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koru_stats', '0010_alter_general_options_alter_charactermonthlyore_isk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactermonthlypvp',
            name='damage_dealt',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactermonthlypvp',
            name='final_blows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactermonthlypvp',
            name='participations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactermonthlypvp',
            name='solo_kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactermonthlypvp',
            name='top_damage_kills',
            field=models.IntegerField(default=0),
        ),
    ]
