# Generated by Django 5.2.15 on 2026-06-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koru_stats', '0018_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpHealthSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_index=True, max_length=7, unique=True)),
                ('n_miembros', models.IntegerField(default=0)),
                ('altas', models.IntegerField(default=0)),
                ('bajas', models.IntegerField(default=0)),
                ('neto', models.IntegerField(default=0)),
                ('churn_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('antiguedad_media_dias', models.IntegerField(default=0)),
                ('n_verde', models.IntegerField(default=0)),
                ('n_amarillo', models.IntegerField(default=0)),
                ('n_naranja', models.IntegerField(default=0)),
                ('n_rojo', models.IntegerField(default=0)),
                ('cobertura_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('participacion_media', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('incidentes', models.IntegerField(default=0)),
                ('indice_salud', models.IntegerField(default=0)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salud de corp (snapshot)',
                'verbose_name_plural': 'Salud de corp (snapshots)',
                'ordering': ['period'],
            },
        ),
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Puede ver Estadísticas y Mi Dashboard'), ('corp_finance_access', 'Puede ver Finanzas Corp'), ('moon_tax_access', 'Puede ver Tax Lunas'), ('moon_tax_admin', 'Puede gestionar tax de lunas'), ('pvp_access', 'Puede ver estadísticas PvP detalladas'), ('fc_access', 'Puede ver panel FC/Director'), ('auditor_access', 'Puede ver el panel Auditor (seguridad)'), ('auditor_admin', 'Puede configurar el Auditor y revisar/descartar alertas'), ('auditor_corp_health', 'Puede ver el panel de Salud de Corp (Directores/CEO)'), ('tickets_reclutamiento', 'Tickets: ve Reclutamiento'), ('tickets_directores', 'Tickets: ve A Directores'), ('tickets_asuntos_internos', 'Tickets: ve Asuntos Internos'), ('tickets_it', 'Tickets: ve IT y Soporte'), ('tickets_admin', 'Tickets: ve todos los tipos'))},
        ),
        migrations.CreateModel(
            name='CohortRetention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohorte', models.CharField(db_index=True, max_length=7)),
                ('offset_meses', models.IntegerField()),
                ('base', models.IntegerField(default=0)),
                ('retenidos', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Retencion por cohorte',
                'verbose_name_plural': 'Retencion por cohorte',
                'ordering': ['cohorte', 'offset_meses'],
                'constraints': [models.UniqueConstraint(fields=('cohorte', 'offset_meses'), name='uniq_cohort_offset')],
            },
        ),
    ]
